# Dependencies
markdown:         kramdown
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            1ain
tagline:          'Present day, present time.'
description:      "Welcome to iwakura1ain's personal blog. For more info about me, please visit the about page."

# github
url:              "https://iwakura1ain.github.io"
baseurl:          "https://iwakura1ain.github.io"

# local
# url:              ""
# baseurl:          ""



paginate:         5
paginate_path: '/page:num'

#Custom vars
version:          2.1.0

github:
  repo:           https://github.com/iwakura1ain/
