#+STARTUP: showall indent
#+OPTIONS: toc:nil
#+OPTIONS: org-export-with-smart-quotes
#+OPTIONS: org-export-with-emphasize
#+OPTIONS: org-export-with-timestamps
#+BEGIN_EXPORT html
---
layout: post #jekyll layout
title: "Review of Cyberpunk Edgerunners" #title 
date:   2022-09-15 18:59:05 +0900
categories: #specify post category (space seperated string)
tags: #specify post tags (space seperated string)
#variable: val -> use as {{page.variable}}
---
#+END_EXPORT

* Review of Cyberpunk Edgerunners

<img src ="../public/img/d.jpeg" align="center" width="300" height="250" class="img" />

The cyberpunk genre has always had a special place in my heart. Near-future aesthetics combined with extreme interpretations of capitalist thought etc etc; it rings all of my bells. And with the release of cyerpunk edgerunners I feel like this genre has had an incredible addition to it's stagnating archive of content. Now more about the show itself.

Cyberpunk edgerunners is set in the famous cyberpunk universe by Mike Pondsmith, and as such the lore of the show feels much richer than just a one-off show. And the story is about a street kid turned cyberpunk(or edgerunner) and his eventual demise. It's a classic cyberpunk story, done many times by previous cyberpunk authors and creators, but the execution and the character interactions pull through and make it feel fresh. 

The thing that struck me about this show was the artstyle and how it captured the aesthetic of night city so well. Harsh neon lights, exaggerated cybernetics, gore; all of it is drawn so viscreally in the animated artstyle from Studio Trigger. Some of the action scenes with dynamic character movement might feel a bit janky when compared to the intimate stills and close-up moments, but theyre all done well enough for it to not be an eyesore.

Overall, I'd give this show a 9/10. A must watch if you're into cyberpunk or just want to see an action anime .










